### ISSUE TITLE
Allow linking notes to specific Tasks

### ISSUE THREAD

**Issue by CaAlden** [CaAlden/bullet-journal#10]
Notes _are_ valid as top level entries in the bullet journal, but often the pertain only to a single task and should always be carried with that task.

### Tasks for resolving this:

 - [ ] Add notes to entries as an array of note tasks
 - [ ] Create a UI for attaching notes to a task
    1. Create a new note attached to a task
    2. Attach an existing top level note to a task
 - [ ] Create a ui for rendering notes as elements below a given task.

**Comment by CaAlden** [comment]
I'm realizing that "Sub Entries" is sort of the real feature I want. The ability to break up a task into multiple elements with potentially attached notes. It would additionally be nice to create a sort of topology in the sub tasks so you could define some ordering of things that must happen before others.
